from ShortPath import ShortPath
from mst import kruskal


s = ShortPath()
print(s.start, s.arrive)
kruskal_minumim_spanning_tree = kruskal(s.graph1)
space = "-" * 50
print()
print("Dijkstra's Algorithm Time")
print(space)
s.dijkstra_algorithm_time(s.graph1)
print()
print("Dijkstra's Algorithm Stops")
print(space)
s.dijkstra_algorithm_stops(s.graph2)
print()
print("Bfs Algorithm")
print(space)
s.bfs_algo(s.graph2)
print()
print("List of edges that is possible to close:")
print(space)
s.kruskal_algorithm(s.graph1)
print()
print("Dijkstra's Algorithm time after Kruskal's Algorithm")
print(space)
s.dijkstra_algorithm_time(kruskal_minumim_spanning_tree)
print()
print("Dijkstra's Algorithm stops after Kruskal's Algorithm")
print(space)
s.dijkstra_algorithm_stops(kruskal_minumim_spanning_tree)
print()
print("Bfs Algorithm after Kruskal's Algorithm")
print(space)
s.bfs_algo(kruskal_minumim_spanning_tree)